### ISSUE TITLE
Undefined symbols on iPad (3.2) and iPhone 4 SDK

### ISSUE THREAD

**Issue by caged** [caged/httpriot#1]
The @synchronized block in HROperationQueue is causing the compiler to complain about undefined symbols.  Removing the @synchronized block (not desirable) allows everything to compile and run just fine.

Undefined symbols:
        "___restore_vfp_d8_d15_regs", referenced from:
        +[HROperationQueue sharedOperationQueue] in libhttpriot.a(HROperationQueue.o)
        "___save_vfp_d8_d15_regs", referenced from:
        +[HROperationQueue sharedOperationQueue] in libhttpriot.a(HROperationQueue.o)
     ld: symbol(s) not found 
     collect2: ld returned 1 exit status

This isn't local to HTTPRiot.  I was able to reproduce it in this project - http://github.com/Caged/SyncError

**Comment by chapados** [comment]
It's not your code.  This is a problem with your build settings.  For iPad (and maybe iPhone OS4) you need to make sure that you are building an armv7 compatible binary for your library. Right now, lipo -info says it is only armv6.

 Open the SyncTestLib project settings and change the Architectures pull-down to Optimized (armv6, armv7).  You should also change it in the Target settings to:
Click on the 'TestSyncLib' under the 'Targets' section, open the info inspector, and make sure you choose Optimized.

After making these two changes I was able to build it for iPad.

cheers,

Brian

**Comment by caged** [comment]
Thanks Brian, this worked great!

**Comment by jterhorst** [comment]
I'm still seeing this on iPhone OS 4, though it works fine on iPad. I already have this setting changed - is there something else I can do to check on this for OS 4.0?

**Comment by chapados** [comment]
I haven't installed the iPhoneOS4 SDK yet, so I can't check that for you.  However, this error is typically always related to your Build settings.  Maybe double-check that the base SDK is set correctly in both projects?
