### ISSUE TITLE
Fails to build on newest Xcode and SDK 4.0

### ISSUE THREAD

**Issue by topfunky** [caged/httpriot#4]
After installing the new Xcode for iOS SDK 4.0, I can't figure out how to build httpriot on the 4.0 SDK. As I use httpriot in all my iPhone projects, this is something I'd like to figure out. Build errors here:

```
http://peepcode.com/system/uploads/2010/20100625-build-error.png
```

I tried setting the Base SDK to various values of SDK 3.2 and 4.0, but all with the same errors that you see here.
1. Install newest iOS 4.0 SDK
2. Get info on my application's target and change the Base SDK to "iPhone Simulator 4.0" for the current configuration
3. Error appears as shown above

Any ideas?

**Comment by pierrevalade** [comment]
I also have the same problem.
Thanks.

**Comment by noahhendrix** [comment]
The really interesting thing, for me (and I assume you too), is that it builds just fine for the iPhone Device.

**Comment by caged** [comment]
I've been on vacation.  Just downloaded iOS4.  If everything goes well, I hope to have a build for it today.

**Comment by noahhendrix** [comment]
Thanks, I appreciate all the work you've done on this great library. It let's me get a real application up in running in less than a day.

**Comment by caged** [comment]
OK, new build is up for iOS4.0.

topfunky: you might also want to make sure -all_load is included in "Other Linker Flags".

**Comment by topfunky** [comment]
Wow, thanks for the quick response. Works like a dream!

The new build worked without -all_load, but I'll try it anyway at your suggestion.

**Comment by pierrevalade** [comment]
Thanks!
