### ISSUE TITLE
EXC_BAD_INSTRUCTION on Pre-3GS Devices

### ISSUE THREAD

**Issue by noahhendrix** [caged/httpriot#5]
When I use the latest version of the library (0.6.11) on pre-3GS devices I get the following error
    Program received signal:  “EXC_BAD_INSTRUCTION”.

It then shows me line 39 of HRRestModel.m
        if(dict) {

It has shown me line 23
        if(!attributes)

It apparently doesn't like
    static NSDictionary *attributes;

Any ideas?

**Comment by noahhendrix** [comment]
I can also confirm this is the case with the example application, doesn't work on iPod Touch 2G, does on iPhone 3GS

**Comment by noahhendrix** [comment]
In the interim I deployed using version 0.6.10, as it works on all devices, but not in simulator.

**Comment by bricooke** [comment]
I'm seeing the same thing. Thanks for the post about 0.6.10 working, that should do for me as well so long as it works in iOS 4.

**Comment by pierrevalade** [comment]
I confirm this issue. I also confirm that you can use 0.6.10 on all devices (but not in simulator 4.0).
@Caged : Are you aware ?

Thanks

**Comment by rlocklear** [comment]
I have also confirmed. Any news on a fix?

**Comment by pierrevalade** [comment]
0.6.10 doesn't work with the lastest version of iOS >= 4.1
This broke my app.
0.6.11 works well on simulator (4.1, 4.2) and my device (4.0).

Do you still have issues with 0.6.11 on Pre-3GS Devices ?

**Comment by denis** [comment]
I have this issue with iPhone 2G and httpriot 0.6.11:

```
Program received signal:  “EXC_BAD_INSTRUCTION”.
Xcode could not locate source file: HRRestModel.m (line: 23)
```
